/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chloe' at '5/22/17 12:40 AM' with Gradle 2.14.1
 *
 * @author chloe, @date 5/22/17 12:40 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
